language: node_js
node_js: stable
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: 'XJXrqmCYGyUIcJXp9Nv5dt+SZ9rDrLwnEWspjQ1g1o66JXQSe3h0F1zUamzp7BVy4nhOnmIt2LLnFZVXdrYZunYpoGQJxN4ck2ajvmU0IZfzCnPDD3IdW8m9SEFLvCMHk0lb9YCMTyKQ5LQCifqkI1Zw3ZPKGCIE6DcHwpmQLr+iL9nlLO62gylTT0u/GQPded80pq4lNEm+Xzw21NRBhdzY4n+Mqw6hJyXgPgk9uoTlVTJCZeBSHXwqSb8pv30Mb1BXDRvn/g30GcpFZQ89+lHDpROqKl9xlL8M7xwnx69/kX2Rd1edOqYuBir5ViQDZisGHYoup6paYjldSi1fKuZh4PCknJeR3KKmHYpOIOC1OiKk71p9TSSmJOmv3PZ7UwijO/CmpxWq4mraPDzt5Oyu8dp3mxlhAmwe8eYGA0iS0mnsHp3M+25HTKtWFIuTZxb2EK24mGM4LqCUUIznVbExTa/ml9j1/22B6SsJvzx/JrVA/n7c+9HXV/5WJqlyp4j/+8bcjvws+O8V0/Vm5Cyf0xGkYZD/PM09Os6qncJRpEK2rWjR0A8LiNWCgbeUzoC4WSVwO9IdFGbN4kVfgSehO0101TZd0r7I759fnH5lJI2kpFh+BeHmInv2wcUvaajF58GgHEKmc9LXvi0fQO9KTFmqLPFNDOEq5fvBorU='
branches:
  only:
    - master
